### ISSUE TITLE
Search through database

### ISSUE THREAD

**Issue by haveanicedey** [tgirotto/elastic_search#1]
- Search modules for artist and song name search 
> Command line approach rather than browser based is preferred

**Comment by tgirotto** [comment]
I updated the readme to explain how to look for songs through the list. actually pretty nice, because i realised that elastic search also interprets the '+' expression in the strings as an OR. Also, it returns the time taken to complete the process. Still working on the rest.

**Comment by haveanicedey** [comment]
- Also can you set up the working environment in the server? And export all your code there from now on?

**Comment by tgirotto** [comment]
yes I've already cloned this into the server. Now I am working on the database dump, so I can push that to the server also.

**Comment by tgirotto** [comment]
If we need anything else related to search, just open new issues :)
